:: create_palettes_executor.bat titan_0.png <num_perm_instances>
:: Kill them all: open new cmd and run: taskkill /f /fi "imagename eq aseprite.exe"
@ECHO OFF
SETLOCAL enabledelayedexpansion

SET IMAGE=%1
FOR %%i IN ("%IMAGE%") DO SET "IMAGE_FILENAME=%%~ni"
SET "TARGET_PATH=%~p1"
IF "%TARGET_PATH%" == "" SET TARGET_PATH=.
SET SOLUTION_IMAGE_FILE=%TARGET_PATH%%IMAGE_FILENAME%_RGB.png
:: delete solution image generated by the LUA script
DEL /F /Q %SOLUTION_IMAGE_FILE% >NUL 2>&1

:: How many permutation instances do we need to execute
SET M=%2
SET N=%NUMBER_OF_PROCESSORS%
:: up to 16 processes
IF %N% GTR 16 SET N=16
IF %N% GTR %M% SET N=%M%

ECHO 222222222222222222222222222222222222222222222
ECHO Using batches of %N% processes each.
ECHO 222222222222222222222222222222222222222222222
ECHO:

SET /A "rand=%RANDOM% %% 100000 + 1"
SET tempFileExt=creatorTMP_%rand%
IF "%tempFileExt%" == "" (
  ECHO No temp file extension could be created
  EXIT /B
)
SET tmpDir=creatorTMP_
MKDIR %tmpDir% >NUL 2>&1
DEL /F /Q %tmpDir%\* >NUL 2>&1

SET /A "NUM_BATCHES=(M+N-1)/N"
SET /A "numProc=1"
FOR /L %%i IN (1,1,%NUM_BATCHES%) DO (
  FOR /L %%j IN (1,1,%N%) DO (
    IF !numProc! leq !M! (
      ECHO !numProc! > %tmpDir%\!numProc!.%tempFileExt%
      start /B cmd /C "aseprite -b %IMAGE% -script-param ID_PROC=!numProc! --script create_palettes_for_md.lua & DEL /F /Q %tmpDir%\!numProc!.%tempFileExt% >NUL 2>^&1"
      :: wait 7 ms before execute next process
      ping -N 1 -W 7 127.0.0.1 >NUL
    )
	SET /A "numProc=numProc+1"
  )
  :: wait until current batch finishes
  :waitloop
  IF EXIST %tmpDir%\*.%tempFileExt% (
    timeout /t 2 /nobreak >NUL
    :: check if solution was generated
    IF exist %SOLUTION_IMAGE_FILE% (
      taskkill /F /FI "imagename eq aseprite.exe" >NUL 2>&1
      GOTO done
    )
    GOTO waitloop
  )
)

:done

DEL /F /Q %tmpDir%\* >NUL 2>&1
RMDIR %tmpDir% >NUL 2>&1

ECHO:
ECHO 222222222222222222222222222222222222222222222
ECHO All batches complete.
ECHO 222222222222222222222222222222222222222222222
ECHO:

EXIT /B 0